development:
  database: frontend_development
  host: localhost

<% if ENV['MONGOHQ_URL'] %>
<% uri = URI.parse(ENV['MONGOHQ_URL']) %>
production:
  database: <%= uri.path.sub('/','') %>
  username: <%= uri.user %>
  password: <%= uri.password %>
  hosts: <%= uri.host %>
  port: <%= uri.port %>
<% end %>
